---
name: build self-contained READMEs

"on":
  push:

permissions:
  contents: read

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: check out the codebase
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.0"

      - name: set up python 3
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4
        with:
          python-version: "3.x"

      - name: setup/activate pre-commit cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: ~/.cache/pre-commit
          key: "${{ hashFiles('.pre-commit-config.yaml') }}"

      - name: install asciidoctor and other relevant ruby gems
        run: gem install --no-document asciidoctor asciidoctor-reducer rouge coderay

      - name: Generate README.adoc using ascidoctor-reducer.
        run: asciidoctor-reducer README.orig.adoc -o README.adoc

      - name: generate README.xml from README.adoc using ascidoctor
        run: asciidoctor -b docbook README.adoc

      - name: Generate README.md from README.xml using pandoc
        uses: docker://pandoc/core@sha256:222badaf55d35aa19a54294721b2669a55737e8a96e78f038b89c2b70bccd13f
        with:
          args: "-f docbook -t markdown_strict README.xml -o README.md --wrap=none"

      - name: pre-commit README.md
        run: |
          python3 -m pip install pre-commit
          pre-commit run --files README.md || true
          pre-commit run --files README.md || true

      - name: get first line of commit message as variable to be used in next step
        shell: bash
        run: |
          echo "FIRST_LINE_OF_HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}" | head -1 >> $GITHUB_ENV
        env:
          HEAD_COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"

      - name: Commit generated READMEs.
        uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80 # tag=v4
        with:
          commit_message: "${{ env.FIRST_LINE_OF_HEAD_COMMIT_MESSAGE }}\n${{ github.sha }}"
          file_pattern: README.adoc README.md
          disable_globbing: true

      - name: Generate HTML
        run: asciidoctor --backend=html5 --destination-dir docs --out-file index.html README.adoc

      - name: Deploy HTML to GitHub Pages (when branch is master).
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # tag=v3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_branch: gh-pages
          publish_dir: ./docs/
        if: github.ref == 'refs/heads/master'
