---
name: build self-contained README
permissions:
  pages: write
  contents: write
"on":
  push:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase
        uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.0"

      - name: install asciidoctor
        run: gem install --no-document asciidoctor asciidoctor-reducer rouge coderay

      - name: Generate README.adoc using ascidoctor-reducer.
        run: asciidoctor-reducer README.orig.adoc -o README.adoc

      - name: Commit generated README.
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ github.event.head_commit.message }}  \n as per ${{ github.sha }}"
          file_pattern: README.adoc
          disable_globbing: true

      - name: Generate HTML
        run: asciidoctor --backend=html5 --destination-dir docs --out-file index.html README.adoc

      - name: Deploy to GitHub Pages (when branch is master)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/
        if: github.ref == 'refs/heads/master'
